const Arr = [
    "/img/img1.jpg",
    "/img/site1.jpg",
    "/img/site3.jpg",
    "/img/site5.jpg",
    "/img/site7.jpg",
    "/img/ui1.jpg",
    "/img/ui2.jpg",
    "/img/ui3.jpg",
    "/img/ui4.jpg",
    "/img/ui5.jpg",
    "/img/ui6.jpg",
    "/img/ui7.jpg",
    "/img/ui8.jpg",
    "/img/ui10.jpg",
    "/img/ui11.jpg",
    "/img/ui12.jpg",
    "/img/ui13.jpg",
    "/img/ui14.jpg",
    "/img/ui16.png",
    "/img/ui17.png",
    "/img/ui18.png",
    "/img/ui19.png",
    "/img/ui22.png",
    "/img/ui23.png",
    "/img/ui24.png",
    "/img/ui25.png",
    "/img/ui26.jpg",
    "/img/ui27.png",
    "/img/ui28.png",
    "/img/img26.jpg",
    "/img/logo1.png",
    "/img/logo2.png",
    "/img/logo3.png",
    "/img/logo4.png",
    "/img/ui29.png",
    "/img/ui30.png",
    "/img/ui31.png",
    "/img/ui32.png",
    "/img/ui33.png",
    "/img/lo.png",
    "/img/img45.jpg",
    "/img/ui34.png",
    "/img/ui35.png",
    "/img/ui36.png",
    "/img/ui37.png",
    "/img/logo5.png",
    "/img/phone1.png",
    "/img/phone2.png",
    "/img/starwars.jpg",
    "/img/site2.jpg",
]
    



export default Arr